/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueSpot.Client.Sdk.Model;
using BlueSpot.Client.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueSpot.Client.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing EnumValueInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnumValueInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnumValueInfo
        //private EnumValueInfo instance;

        public EnumValueInfoTests()
        {
            // TODO uncomment below to create an instance of EnumValueInfo
            //instance = new EnumValueInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnumValueInfo
        /// </summary>
        [Fact]
        public void EnumValueInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnumValueInfo
            //Assert.IsType<EnumValueInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Caption'
        /// </summary>
        [Fact]
        public void CaptionTest()
        {
            // TODO unit test for the property 'Caption'
        }

    }

}
