/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueSpot.Client.Sdk.Model;
using BlueSpot.Client.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueSpot.Client.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing FileInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileInfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileInfoResponse
        //private FileInfoResponse instance;

        public FileInfoResponseTests()
        {
            // TODO uncomment below to create an instance of FileInfoResponse
            //instance = new FileInfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileInfoResponse
        /// </summary>
        [Fact]
        public void FileInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileInfoResponse
            //Assert.IsType<FileInfoResponse>(instance);
        }


        /// <summary>
        /// Test the property 'FileRef'
        /// </summary>
        [Fact]
        public void FileRefTest()
        {
            // TODO unit test for the property 'FileRef'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

    }

}
