/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueSpot.Client.Sdk.Model;
using BlueSpot.Client.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueSpot.Client.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing MetaClassInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetaClassInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MetaClassInfo
        //private MetaClassInfo instance;

        public MetaClassInfoTests()
        {
            // TODO uncomment below to create an instance of MetaClassInfo
            //instance = new MetaClassInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetaClassInfo
        /// </summary>
        [Fact]
        public void MetaClassInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" MetaClassInfo
            //Assert.IsType<MetaClassInfo>(instance);
        }


        /// <summary>
        /// Test the property 'EntityName'
        /// </summary>
        [Fact]
        public void EntityNameTest()
        {
            // TODO unit test for the property 'EntityName'
        }
        /// <summary>
        /// Test the property 'Ancestor'
        /// </summary>
        [Fact]
        public void AncestorTest()
        {
            // TODO unit test for the property 'Ancestor'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

    }

}
