/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueSpot.Client.Sdk.Model;
using BlueSpot.Client.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueSpot.Client.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing QueryInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueryInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QueryInfo
        //private QueryInfo instance;

        public QueryInfoTests()
        {
            // TODO uncomment below to create an instance of QueryInfo
            //instance = new QueryInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueryInfo
        /// </summary>
        [Fact]
        public void QueryInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" QueryInfo
            //Assert.IsType<QueryInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Jpql'
        /// </summary>
        [Fact]
        public void JpqlTest()
        {
            // TODO unit test for the property 'Jpql'
        }
        /// <summary>
        /// Test the property 'EntityName'
        /// </summary>
        [Fact]
        public void EntityNameTest()
        {
            // TODO unit test for the property 'EntityName'
        }
        /// <summary>
        /// Test the property 'ViewName'
        /// </summary>
        [Fact]
        public void ViewNameTest()
        {
            // TODO unit test for the property 'ViewName'
        }
        /// <summary>
        /// Test the property 'FetchPlanName'
        /// </summary>
        [Fact]
        public void FetchPlanNameTest()
        {
            // TODO unit test for the property 'FetchPlanName'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'Cacheable'
        /// </summary>
        [Fact]
        public void CacheableTest()
        {
            // TODO unit test for the property 'Cacheable'
        }
        /// <summary>
        /// Test the property 'AnonymousAllowed'
        /// </summary>
        [Fact]
        public void AnonymousAllowedTest()
        {
            // TODO unit test for the property 'AnonymousAllowed'
        }
        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }

    }

}
