/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueSpot.Client.Sdk.Model;
using BlueSpot.Client.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueSpot.Client.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing RestServiceInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RestServiceInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RestServiceInfo
        //private RestServiceInfo instance;

        public RestServiceInfoTests()
        {
            // TODO uncomment below to create an instance of RestServiceInfo
            //instance = new RestServiceInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RestServiceInfo
        /// </summary>
        [Fact]
        public void RestServiceInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RestServiceInfo
            //Assert.IsType<RestServiceInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Methods'
        /// </summary>
        [Fact]
        public void MethodsTest()
        {
            // TODO unit test for the property 'Methods'
        }

    }

}
