/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueSpot.Client.Sdk.Model;
using BlueSpot.Client.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueSpot.Client.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing RestMethodParamInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RestMethodParamInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RestMethodParamInfo
        //private RestMethodParamInfo instance;

        public RestMethodParamInfoTests()
        {
            // TODO uncomment below to create an instance of RestMethodParamInfo
            //instance = new RestMethodParamInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RestMethodParamInfo
        /// </summary>
        [Fact]
        public void RestMethodParamInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RestMethodParamInfo
            //Assert.IsType<RestMethodParamInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

    }

}
