/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueSpot.Client.Sdk.Model;
using BlueSpot.Client.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueSpot.Client.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing RestMethodInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RestMethodInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RestMethodInfo
        //private RestMethodInfo instance;

        public RestMethodInfoTests()
        {
            // TODO uncomment below to create an instance of RestMethodInfo
            //instance = new RestMethodInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RestMethodInfo
        /// </summary>
        [Fact]
        public void RestMethodInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RestMethodInfo
            //Assert.IsType<RestMethodInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'HttpMethod'
        /// </summary>
        [Fact]
        public void HttpMethodTest()
        {
            // TODO unit test for the property 'HttpMethod'
        }
        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }

    }

}
