/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BlueSpot.Client.Sdk.Model;
using BlueSpot.Client.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BlueSpot.Client.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ShortPermissionInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShortPermissionInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShortPermissionInfo
        //private ShortPermissionInfo instance;

        public ShortPermissionInfoTests()
        {
            // TODO uncomment below to create an instance of ShortPermissionInfo
            //instance = new ShortPermissionInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShortPermissionInfo
        /// </summary>
        [Fact]
        public void ShortPermissionInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShortPermissionInfo
            //Assert.IsType<ShortPermissionInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
