/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using BlueSpot.Client.Sdk.Client;
using BlueSpot.Client.Sdk.Api;

namespace BlueSpot.Client.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing DocumentationControllerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DocumentationControllerApiTests : IDisposable
    {
        private DocumentationControllerApi instance;

        public DocumentationControllerApiTests()
        {
            instance = new DocumentationControllerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentationControllerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DocumentationControllerApi
            //Assert.IsType<DocumentationControllerApi>(instance);
        }

        /// <summary>
        /// Test GetOpenApiJson
        /// </summary>
        [Fact]
        public void GetOpenApiJsonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetOpenApiJson();
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test GetOpenApiYaml
        /// </summary>
        [Fact]
        public void GetOpenApiYamlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetOpenApiYaml();
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test GetProjectOpenApiJson
        /// </summary>
        [Fact]
        public void GetProjectOpenApiJsonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetProjectOpenApiJson();
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test GetProjectOpenApiYaml
        /// </summary>
        [Fact]
        public void GetProjectOpenApiYamlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetProjectOpenApiYaml();
            //Assert.IsType<string>(response);
        }
    }
}
