/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using BlueSpot.Client.Sdk.Client;
using BlueSpot.Client.Sdk.Api;
// uncomment below to import models
//using BlueSpot.Client.Sdk.Model;

namespace BlueSpot.Client.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing EnumsControllerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EnumsControllerApiTests : IDisposable
    {
        private EnumsControllerApi instance;

        public EnumsControllerApiTests()
        {
            instance = new EnumsControllerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnumsControllerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EnumsControllerApi
            //Assert.IsType<EnumsControllerApi>(instance);
        }

        /// <summary>
        /// Test GetAllEnumInfos
        /// </summary>
        [Fact]
        public void GetAllEnumInfosTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllEnumInfos();
            //Assert.IsType<List<EnumInfo>>(response);
        }

        /// <summary>
        /// Test GetEnumInfo
        /// </summary>
        [Fact]
        public void GetEnumInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string enumClassName = null;
            //var response = instance.GetEnumInfo(enumClassName);
            //Assert.IsType<EnumInfo>(response);
        }
    }
}
