/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using BlueSpot.Client.Sdk.Client;
using BlueSpot.Client.Sdk.Api;

namespace BlueSpot.Client.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing MessagesControllerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MessagesControllerApiTests : IDisposable
    {
        private MessagesControllerApi instance;

        public MessagesControllerApiTests()
        {
            instance = new MessagesControllerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessagesControllerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MessagesControllerApi
            //Assert.IsType<MessagesControllerApi>(instance);
        }

        /// <summary>
        /// Test GetLocalizationForAllEntities
        /// </summary>
        [Fact]
        public void GetLocalizationForAllEntitiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetLocalizationForAllEntities();
            //Assert.IsType<Dictionary<string, string>>(response);
        }

        /// <summary>
        /// Test GetLocalizationForAllEnums
        /// </summary>
        [Fact]
        public void GetLocalizationForAllEnumsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetLocalizationForAllEnums();
            //Assert.IsType<Dictionary<string, string>>(response);
        }

        /// <summary>
        /// Test GetLocalizationForEntity
        /// </summary>
        [Fact]
        public void GetLocalizationForEntityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string entityName = null;
            //var response = instance.GetLocalizationForEntity(entityName);
            //Assert.IsType<Dictionary<string, string>>(response);
        }

        /// <summary>
        /// Test GetLocalizationForEnum
        /// </summary>
        [Fact]
        public void GetLocalizationForEnumTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string enumClassName = null;
            //var response = instance.GetLocalizationForEnum(enumClassName);
            //Assert.IsType<Dictionary<string, string>>(response);
        }
    }
}
