/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using BlueSpot.Client.Sdk.Client;
using BlueSpot.Client.Sdk.Api;

namespace BlueSpot.Client.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing VersionControllerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class VersionControllerApiTests : IDisposable
    {
        private VersionControllerApi instance;

        public VersionControllerApiTests()
        {
            instance = new VersionControllerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VersionControllerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' VersionControllerApi
            //Assert.IsType<VersionControllerApi>(instance);
        }

        /// <summary>
        /// Test GetApiVersion
        /// </summary>
        [Fact]
        public void GetApiVersionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetApiVersion();
            //Assert.IsType<string>(response);
        }
    }
}
