openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://bluespotserver.nw.r.appspot.com
paths:
  /public/test/{uuid}:
    get:
      operationId: getPart
      parameters:
      - explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
      summary: Returns a Hello World message
      tags:
      - test-controller
components:
  schemas: {}

