openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:8080
paths:
  /api/public/debug/hash/{input}:
    get:
      operationId: hash
      parameters:
      - explode: false
        in: path
        name: input
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: OK
      summary: Public debug api that returns a hash
      tags:
      - debug-controller
  /api/debug/hash/{input}:
    get:
      operationId: hash2
      parameters:
      - explode: false
        in: path
        name: input
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: OK
      summary: Private debug api that returns a hash
      tags:
      - debug-controller
components:
  schemas: {}

